# включает privileged: true
apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
        privileged: true