# запускается от root (UID 0)
apiVersion: v1
kind: Pod
metadata:
  name: pod-root-user
  namespace: audit-zone
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
        allowPrivilegeEscalation: true