apiVersion: v1
kind: Pod
metadata:
  name: pod-secure-root-user
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: [ "ALL" ]
        seccompProfile:
          type: RuntimeDefault
  securityContext:
    runAsNonRoot: true